# Generated by Django 4.2.15 on 2024-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('palabra', models.CharField(max_length=100)),
                ('tiempo', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
